# Generated by Django 5.1.1 on 2026-04-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncTarget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this target.", max_length=200
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("search", "Saved search (API v4)"),
                            ("docket", "Docket by ID"),
                        ],
                        default="search",
                        max_length=16,
                    ),
                ),
                (
                    "query_string",
                    models.TextField(
                        blank=True,
                        help_text="For searches: URL query string (e.g. type=o&q=...). Ignored for docket kind.",
                    ),
                ),
                (
                    "remote_docket_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For docket kind: CourtListener docket primary key.",
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("ok", "Completed"),
                            ("error", "Failed"),
                        ],
                        default="started",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("hits_fetched", models.PositiveIntegerField(default=0)),
                ("files_downloaded", models.PositiveIntegerField(default=0)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="research_sync.synctarget",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LocalHit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("cluster", "Opinion cluster"),
                            ("opinion", "Opinion"),
                            ("docket", "Docket"),
                            ("other", "Other"),
                        ],
                        default="cluster",
                        max_length=16,
                    ),
                ),
                (
                    "remote_cluster_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "remote_opinion_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "remote_docket_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("court_id", models.CharField(blank=True, max_length=15)),
                (
                    "docket_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "remote_detail_url",
                    models.URLField(
                        blank=True,
                        help_text="Best-effort link to the resource on CourtListener.",
                        max_length=800,
                    ),
                ),
                (
                    "remote_pdf_url",
                    models.URLField(blank=True, max_length=800),
                ),
                (
                    "local_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional downloaded PDF on this machine.",
                        max_length=500,
                        upload_to="research_sync/pdfs/%Y/%m/",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Subset of API response for offline context.",
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "dedupe_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stable id for upserts, e.g. cluster-123 or opinion-456.",
                        max_length=120,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hits",
                        to="research_sync.syncrun",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="research_sync.synctarget",
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "is_read"],
                        name="research_sy_target__148cad_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target", "dedupe_key"),
                        name="research_sync_localhit_target_dedupe",
                    )
                ],
            },
        ),
    ]
